module.exports = {
  "ALIVE_IMG": "https://i.ibb.co/BHsMbKHv/2713.jpg",
  "PREFIX": ".",
  "AUTO_READ_STATUS": true,
  "MODE": "privet",
  "BOT_NUMBER": "94716682532",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": true,
  "AUTO_VOICE": false,
  "AUTO_STICKER": false,
  "AUTO_REPLY": true,
  "AUTO_REACT": false,
  "WELCOME": false,
  "ANTI_BAD": false,
  "ANTI_BOT": false,
  "ANTI_LINK": false,
  "ANTI_CALL": false,
  "ANTI_DELETE": true,
  "ALLWAYS_ONLINE": false,
  "MOROCCO_BLOCK": true,
  "BTN_MSG": false,
  "OWNER_NAME": "ＣＲＡＷＬ",
  "NEWS_JID": "false",
  "MOVIE_JID": false,
  "ANIME_JID": false,
  "AUTO_TYPING": false,
  "AUTO_RECORDING": true,
  "AUTO_NEWS": false,
  "OWNER_REACT": false,
  "EMOJI": "👨‍💻",
  "AI_MODE": false,
  "BANNED": [],
  "SUDO": [
    "94716682532"
  ]
};
